version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - evalphobia
  assignees:
  - evalphobia
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.1
    - 1.37.10
    - 1.37.11
    - 1.37.12
    - 1.37.13
    - 1.37.14
    - 1.37.15
    - 1.37.16
    - 1.37.17
    - 1.37.18
    - 1.37.19
    - 1.37.2
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.23
    - 1.37.24
    - 1.37.25
    - 1.37.26
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.3
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.37.4
    - 1.37.6
    - 1.37.7
    - 1.37.8
    - 1.37.9
    - 1.38.0
    - 1.38.1
    - 1.38.10
    - 1.38.12
    - 1.38.13
    - 1.38.14
    - 1.38.15
    - 1.38.16
    - 1.38.17
    - 1.38.18
    - 1.38.19
    - 1.38.21
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.27
    - 1.38.28
    - 1.38.3
    - 1.38.8
  - dependency-name: github.com/aliyun/alibaba-cloud-sdk-go
    versions:
    - 1.61.1000
    - 1.61.1004
    - 1.61.1007
    - 1.61.1008
    - 1.61.1015
    - 1.61.1016
    - 1.61.1018
    - 1.61.1020
    - 1.61.1028
    - 1.61.1032
    - 1.61.1035
    - 1.61.1037
    - 1.61.1042
    - 1.61.1047
    - 1.61.1051
    - 1.61.888
    - 1.61.898
    - 1.61.902
    - 1.61.905
    - 1.61.910
    - 1.61.913
    - 1.61.920
    - 1.61.946
    - 1.61.947
    - 1.61.948
    - 1.61.950
    - 1.61.954
    - 1.61.957
    - 1.61.962
    - 1.61.971
    - 1.61.973
    - 1.61.975
    - 1.61.976
    - 1.61.977
    - 1.61.979
    - 1.61.981
    - 1.61.985
    - 1.61.991
    - 1.61.995
  - dependency-name: cloud.google.com/go
    versions:
    - 0.75.0
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.80.0
  - dependency-name: go.mongodb.org/mongo-driver
    versions:
    - 1.4.5
    - 1.4.6
    - 1.5.0
  - dependency-name: github.com/elastic/go-elasticsearch/v7
    versions:
    - 7.10.0
    - 7.11.0
  - dependency-name: github.com/Azure/go-autorest/autorest
    versions:
    - 0.11.17
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/dockerfiles/ubuntu"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.buster
    - 3.9.2.pre.buster
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
    - 6.11.2
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: docker
  directory: "/dockerfiles/alpine"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.alpine
    - 3.9.2.pre.alpine
