name: Dependency Check

on: push

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      id: snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        SNYK_RESULT=$(snyk monitor --file=go.mod)
        echo ::set-output name=result::${SNYK_RESULT}

    - name: Post as comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNYK_RESULT: ${{ steps.snyk.outputs.result }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"Snyk Result: ${SNYK_RESULT}\"}" \
             ${URL}

