name: Dependency Check

on: push

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      id: snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: >-
          --file=go.mod
          --severity-threshold=medium
          > snyk_result.txt 2>&1
          | tee snyk_result.txt

    - name: Post as comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"Snyk Result: $(cat snyk_result.txt)\"}" \
             ${URL}

